title_primary: "随风浪敛，守拙求真" # the bigger text
title_secondary: "PolarRegionLee's Blog" # the smaller text
keywords:

twitter: PolarRegionLee
# rss: atom.xml
# weibo: PolarRegionLee
instagram: PolarRegionLee
github: PolarRegionLee

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: auto # light/dark/auto (auto follows system preference)

# Giscus comment system
giscus:
  repo: "PolarRegionLee/polarregionlee.github.io"
  repo_id: "R_kgDOQewrBg"
  category: "Announcements"
  category_id: "DIC_kwDOQewrBs4CzKC1"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "preferred_color_scheme"
  lang: "zh-CN"